# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a559096eb5bfadf94f287bfbb90ee87a15f33b28054c971c061d44d2ecdd609f91b450807d15264038dd052c67178a23f236a875003b31f56f188413d92fcd3

test:
  secret_key_base: 30d98a74fbf5688872e7966ccf08c79609771aa3f8c891656dd940d6f079a270d1864a4ad4e5a65bb0c5d49d3a95fb606f4740c8a726ca08ae96cef215929a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
